ci:
  skip: [pylint]
  autofix_prs: true
  autoupdate_schedule: quarterly

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
    -   id: pyupgrade
        args: [--py312-plus]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.15.0'
    hooks:
    -   id: mypy
        args: [--strict]
        additional_dependencies: [pydantic==2.11.3]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.5
  hooks:
    # Run the linter.
    - id: ruff
      args: [--fix]
    # Run the formatter.
    - id: ruff-format
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      args:
        [
          "-rn", # Only display messages
          "-sn", # Don't display the score
          "--rcfile=pyproject.toml",
        ]
- repo: https://github.com/astral-sh/uv-pre-commit
  # uv version.
  rev: 0.6.14
  hooks:
    - id: uv-lock
